from __future__ import annotations

CLASS = 'class'
TREE = 'tree'
CORPSE = 'corpse'
WRECK = 'wreck'
UNITS = 'units'
BUILDINGS = 'buildings'
UNIT = 'Unit'
VEHICLE_WITH_TURRET = 'VehicleWithTurret'
VEHICLE = 'Vehicle'
SOLDIER = 'Soldier'
BUILDING = 'Building'
CONSTRUCTION_SITE = 'construction_site'
RESEARCH_FACILITY = 'research_facility'
PRODUCED_RESOURCE = 'produced_resource'
PRODUCED_UNITS = 'produced_units'
