#!/usr/bin/env python

CURSOR_NORMAL_TEXTURE = 0
CURSOR_FORBIDDEN_TEXTURE = 1
CURSOR_ATTACK_TEXTURE = 2
CURSOR_SELECTION_TEXTURE = 3
CURSOR_MOVE_TEXTURE = 4
CURSOR_REPAIR_TEXTURE = 6
CURSOR_ENTER_TEXTURE = 5
